# Generated by Django 2.0.2 on 2018-04-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='dislikes',
        ),
    ]
