# Generated by Django 2.0.2 on 2018-04-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180416_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
