# Generated by Django 2.0.2 on 2018-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180325_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
