# Generated by Django 2.0.2 on 2018-03-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180325_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AddField(
            model_name='tags',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Questions'),
        ),
    ]
