# Generated by Django 2.0.2 on 2018-04-16 23:31

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180416_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=mainapp.models.Like),
        ),
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=mainapp.models.Like),
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=mainapp.models.Like),
        ),
    ]
