# Generated by Django 2.0.2 on 2018-03-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180326_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='question',
            new_name='tags_question',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='tags_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
