# Generated by Django 2.0.2 on 2018-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180326_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tags_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tags_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='questions',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
