# Generated by Django 2.0.2 on 2018-03-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180326_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
        migrations.AddField(
            model_name='tags',
            name='question',
            field=models.ManyToManyField(to='mainapp.Questions'),
        ),
    ]
