# Generated by Django 2.0.2 on 2018-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180326_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='text',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_text',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
