# Generated by Django 2.0.2 on 2018-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180402_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Your comment'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
