# Generated by Django 2.0.2 on 2018-04-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20180409_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='question',
            field=models.ManyToManyField(to='mainapp.Questions'),
        ),
    ]
