# Generated by Django 2.0.2 on 2018-04-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180409_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag_question',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
