# Generated by Django 2.0.2 on 2018-04-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(to='mainapp.Tags'),
        ),
    ]
