# Generated by Django 2.0.2 on 2018-04-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20180409_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='text',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
