# Generated by Django 2.0.2 on 2018-04-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20180410_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
